# Script to check if the current WSL instance has an Internet Connection.
# If there is no connection, this script will prompt the user for permission
# to overwrite their resolv.conf in an attempt to fix the problem.
#
# This script is meant to be run at the beginning of a script that requires
# an active Internet Connection. Please see connectionStatus.sh for a standalone
# utility script.
#
# Author: Dillon McCardell
# Contact: dillon@alcova.us

#!/bin/bash

# Define a known host (e.g., a public DNS server)
known_host="google.com"

# Ping the known host to check for an internet connection
if ping -c 1 "$known_host" &>/dev/null; then
  # Internet connection is available, do nothing
  echo "Internet connection is available."
else
  while true; do
    # Internet connection failed, print an error message in red text
    echo -e -n "\e[31mInternet Connection failed.\e[0m Modify the resolv.conf in an attempt to fix this? [Y/n]: "
    read answer
    # Convert the user input to lowercase for case-insensitive comparison
    user_input_lower=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
    if [[ "$user_input_lower" == "y" ]]; then

      # Proper contents of the resolv.conf file    
      new_contents="# This file was generated by the cmakeEnvSetup.sh Script as part of the StoryboardIO_Wrapper CMake project
[network]
generateResolvConf = false
nameserver 8.8.8.8"

      # Display the current contents of the resolv.conf file
      echo -e "\n\e[33mPrevious contents of /etc/resolv.conf:\e[0m"
      cat /etc/resolv.conf

      # Overwrite the contents of /etc/resolv.conf with the new contents
      echo "$new_contents" | sudo tee /etc/resolv.conf > /dev/null

      # Display the modified contents of the resolv.conf
      echo -e "\n\e[33mModified /etc/resolv.conf:\e[0m"
      cat /etc/resolv.conf

      if ping -c 1 "$known_host" &>/dev/null; then
        echo -e "\n\e[32mInternet Connection was Established!\n\e[0m"
      else
        echo -e "\n\e[31mInternet Connection failed. Modification of /etc/resolv.conf was not the answer\e[0m"
        echo "Exiting Script"
        exit 1
      fi
      break
    elif [[ "$user_input_lower" == "n" ]]; then
      echo "Exiting script. Internet Connection error needs resolution."
      exit 1
    else
      echo "Invalid input. Please enter 'Y' or 'N'."
    fi
  done
fi